Betting_page/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from Betting_page import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='events:list')),
    path('events/', include('events.urls', namespace='events')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('betting/', include('betting.urls', namespace='betting')),
    path('api/', include('Betting_page.api_urls')),
    path('api/auth', include('rest_framework.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

betting/urls.py
from django.urls import path

from betting import views

app_name = 'betting'

urlpatterns = [
    path('bet_on/<int:event_participant_id>', views.BetCreateView.as_view(), name='create'),

]

events/urls.py
from django.urls import path

from events import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsListView.as_view(), name='list'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
]

events/models.py
from time import sleep

from django.db import models
import requests
from django.db.models import Sum

from django.urls import reverse
from django.utils import timezone
from mptt.fields import TreeForeignKey
from mptt.models import MPTTModel


class EventsParticipant(models.Model):
    event = models.ForeignKey('events.Event', on_delete=models.CASCADE)
    participant = models.ForeignKey('Participant', on_delete=models.CASCADE)
    is_winner = models.BooleanField(default=False)

    class Meta:
        unique_together = ['event', 'participant']


class Category(MPTTModel):
    slug = models.SlugField(unique=True)
    name = models.CharField(max_length=255)
    parent = TreeForeignKey('self', related_name='children', db_index=True, null=True, blank=True,
                            on_delete=models.PROTECT)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('events:category_detail', args=[str(self.pk)])

    class Meta:
        verbose_name_plural = "categories"


class Event(models.Model):
    oh_pk = models.IntegerField(unique=True)
    name = models.CharField(max_length=255)
    start = models.DateTimeField(default=timezone.now)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)

    Active = 'active'
    Finished = 'finished'
    Resolved = 'resolved'
    STATUS_CHOICES = (
        (Active, 'active'),
        (Finished, 'finished'),
        (Resolved, 'resolved'),
    )
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default=Active)

    @classmethod
    def populate(cls):

        count = 0
        current_link = 'https://www.onehash.com/api/events/?limit=30'
        while count <= 6:
            r = requests.get(current_link)
            json_data = r.json()
            events_data = json_data['results']

            for event_data in events_data:
                cls.populate_inner(event_data)
            current_link = json_data['next'] if 'next' in json_data else None
            count += 1

            sleep(0.5)

    @classmethod
    def populate_inner(cls, event_data):
        prev_category = None
        for category_level in event_data['categories']:
            prev_category, created = Category.objects.get_or_create(
                slug=category_level['slug'],
                defaults=dict(parent=prev_category,
                              name=category_level['name']))

        event, created = Event.objects.get_or_create(
            oh_pk=event_data['pk'],
            defaults=dict(name=event_data['name'],
                          start=event_data['start'],
                          category=prev_category))

        for option in event_data['main_bet_type']['options']:
            participant, created = Participant.objects.update_or_create(
                participant_no=option['participant'],
                defaults=dict(name=option['name'],
                              image='https://www.onehash.com' + option['image'] if option['image'] else ''))
            EventsParticipant.objects.update_or_create(participant=participant, event=event)

    @classmethod
    def update_status(cls):
        changed_events = Event.objects.filter(start__lt=timezone.now(), status=Event.Active)
        for event in changed_events:
            r = requests.get(f'https://www.onehash.com/api/events/{event.oh_pk}')
            if r.status_code != 200:
                continue
            json_data = r.json()
            status = json_data['status']
            if status != 'active':
                event.status = 'finished'

            for option in json_data['main_bet_type']['options']:
                if option['won'] == True:
                    event.eventsparticipant_set.filter(participant__participant_no=option['participant']).update(
                        is_winner=True)

            lost_amount = event.eventsparticipant_set.filter(is_winner=False).aggregate(lost=Sum('bets__amount'))[
                'lost']

            winner = event.eventsparticipant_set.filter(is_winner=True).annotate(inbank=Sum('bets__amount')).first()
            if winner:
                event.status = 'resolved'
                for bet in winner.bets.all():
                    user = bet.user
                    wallet = user.wallet
                    wallet.operations.create(change=bet.amount+(bet.amount/winner.inbank)*lost_amount, bet=bet)

            event.save()
            sleep(0.5)

    def get_absolute_url(self):
        return reverse('events:detail', args=[str(self.pk)])


class Participant(models.Model):
    event = models.ManyToManyField('events.Event', through='EventsParticipant', related_name='participants')
    name = models.CharField(max_length=255)
    participant_no = models.IntegerField(unique=True, blank=True, null=True)
    image = models.CharField(max_length=400)

    class Meta:
        ordering = ['name']

events/views.py
from typing import List

from django.db.models import Q, Sum, Count, Prefetch
from django.db.models.functions import Coalesce
from django.views.generic import ListView, DetailView
from rest_framework import viewsets, permissions

from events.models import Event, Category, EventsParticipant
from events.permissions import IsOwnerOrReadOnly
from events.serializers import EventSerializer


class EventsListView(ListView):
    model = Event
    template_name = 'events/event_list.html'
    context_object_name = 'all_events'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.GET.get('archive', None) == 'true':
            return qs.filter(status__in=['finished', 'resolved'])
        else:
            return qs.filter(status='active')

    ordering = ['-start']


class EventDetailView(DetailView):
    model = Event
    template_name = 'events/event_detail.html'
    queryset = Event.objects.annotate(
        inbank=Coalesce(Sum('eventsparticipant__bets__amount'), 0),
        bets_count=Count('eventsparticipant__bets')
    ).prefetch_related(
        Prefetch('eventsparticipant_set',
                 queryset=EventsParticipant.objects.annotate(
                     inbank=Coalesce(Sum('bets__amount'), 0),
                     bets_count=Count('bets')
                 ).select_related('participant'),
                 to_attr='options')
    ).select_related('category__parent__parent')


class CategoryListView(ListView):
    model = Category
    template_name = 'events/category_list.html'
    context_object_name = 'all_categories'


class CategoryDetailView(DetailView):
    model = Category
    template_name = 'events/category_detail.html'

    def get_context_data(self, **kwargs):
        ctx = super().get_context_data(**kwargs)
        # w self.kwargs znajduja sie te argumenty z URLi
        pk = self.kwargs['pk']
        for_category_q = Q(category_id=pk) | Q(category__parent_id=pk) | Q(category__parent__parent_id=pk)
        ctx['events']: List[Event] = list(Event.objects.filter(
            for_category_q
        ))
        ctx['active_count'] = Event.objects.filter(
            for_category_q,
            status='active',
        ).count()
        ctx['finished_count'] = Event.objects.filter(
            for_category_q,
            status='finished',
        ).count()

        return ctx


class EventViewSet(viewsets.ModelViewSet):
    queryset = Event.objects.all()
    serializer_class = EventSerializer
    permission_classes = (permissions.IsAuthenticatedOrReadOnly,
                          IsOwnerOrReadOnly,)

events/templates/events/category_detail.html
{% extends 'base.html' %}

{% block content %}

    <h1>Category Detail View</h1>
    <h1>{{ category.name }}</h1>
    <p><strong>List of active events in this category:</strong></p>
    <ul class="category-list">
        {% for event in events %}
            {% if event.status == 'active' %}
                <li>
                    <a href="{% url 'events:detail' event.pk %}">{{ event.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if active_count == 0 %}
            <p style="color: gray; font-size: 0.8em">There is no active events</p>
        {% endif %}
    </ul>

    <p><strong>List of finished events in this category:</strong></p>
    <ul class="category-list">
        {% for event in events %}
            {% if event.status != 'active' %}
                <li>
                    <a href="{% url 'events:detail' event.pk %}">{{ event.name }}</a>
                </li>
            {% endif %}
        {% endfor %}
        {% if finished_count == 0 %}
            <p style="color: gray; font-size: 0.8em">There is no finished events</p>
        {% endif %}
    </ul>
{% endblock %}

events/templates/events/category_list.html
{% extends 'base.html' %}
{% load mptt_tags %}

{% block content %}
    <ul class="root">
        {% recursetree all_categories %}
            <li class="category-list">
{#                {% if node.is_leaf_node%}#}
                <a href="{{ node.get_absolute_url }}">
{#                    {% endif %}#}
                    {{ node.name }}</a>
                {% if not node.is_leaf_node %}
                    <ul class="children">
                        {{ children }}
                    </ul>
                {% endif %}
            </li>
        {% endrecursetree %}
    </ul>
{% endblock %}

events/templates/events/event_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ event.name }}</h1>
    <p>Bet on this event: {{ event.inbank }} BTC</p>
    <p>Number of bets: {{ event.bets_count }}</p>
    <h2>Options:</h2>
    {% for ep in event.options %}
        {% with p=ep.participant %}
            <p><strong>{{ p.name }}{% if ep.is_winner %} (winner){% endif %}</strong></p>
            {% if p.image %}<p><img src="{{ p.image }}"></p>{% endif %}
            {% if event.status == 'active' %}<a href="{% url 'betting:create' ep.pk %}">
                <button>Bet</button>
            </a>{% endif %}
            <p>Bets on this option: {{ ep.bets_count }}</p>
            <p>Bet on this option: {{ ep.inbank|default_if_none:0 }} BTC</p>
        {% endwith %}
    {% endfor %}
    <br><br>
    <p><strong>Event</strong>:
        <a href="{% url 'events:category_detail' event.category.pk %}" class="tag-link">
            {{ event.category.name }}</a>
    </p>
    <p><strong>Type</strong>:
        {% if event.category.parent %}
            <a href="{% url 'events:category_detail' event.category.parent.pk %}" class="tag-link">
                {{ event.category.parent.name }}
            </a>
        {% endif %}
    </p>
    <p><strong>Activity</strong>:
        {% if event.category.parent.parent %}
            <a href="{% url 'events:category_detail' event.category.parent.parent.pk %}" class="tag-link">
                {{ event.category.parent.parent.name }}</a>
        {% endif %}
    </p>


{% endblock %}

events/templates/events/event_list.html
{% extends 'base.html' %}

{% block content %}
    <h1>Welcome to IndexPage</h1>
    <p>Number of events: {{ all_events.count }}</p>
    {% if request.GET.archive != 'true' %}
        <a href="{% url 'events:list' %}?archive=true ">Show finished events</a>
    {% else %}
        <a href="{% url 'events:list' %}">Go back to active events</a>
    {% endif %}

    <ul class="category-list">
        {% for event in all_events %}
            <li><strong>Name</strong> is:<a href="{{ event.get_absolute_url }}"> {{ event.name }}</a> and
                <strong>pk</strong> is:{{ event.oh_pk }}</li>
        {% endfor %}
    </ul>
{% endblock %}