Betting_page/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from Betting_page import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='events:list')),
    path('events/', include('events.urls', namespace='events')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('betting/', include('betting.urls', namespace='betting')),
    path('api/', include('Betting_page.api_urls')),
    path('api/auth', include('rest_framework.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('wallet/', views.WalletInfo.as_view(), name='wallet'),
]

events/urls.py
from django.urls import path

from events import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsListView.as_view(), name='list'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
]

accounts/models.py
from django.conf import settings
from django.db import models
from django.utils import timezone


class Operation(models.Model):
    date = models.DateTimeField(default=timezone.now)
    change = models.DecimalField(max_digits=15, decimal_places=5)
    wallet = models.ForeignKey('Wallet', on_delete=models.CASCADE, related_name='operations')
    bet = models.ForeignKey('betting.Bet', on_delete=models.CASCADE, related_name='operations')


class Wallet(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, related_name='wallet')

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from accounts.models import Wallet


class UserCreateForm(UserCreationForm):
    class Meta:
        fields = ('username', 'email', 'password1', 'password2')
        model = get_user_model()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display name'
        self.fields['email'].label = 'Email address'

    def save(self, commit=True):
        user = super().save(commit=commit)
        if commit:
            Wallet.objects.create(user=user)
        return user

accounts/views.py
from django.db.models import Sum, Prefetch
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, TemplateView

from accounts.models import Wallet, Operation
from . import forms


class SignUp(CreateView):
    form_class = forms.UserCreateForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


class WalletInfo(TemplateView):
    template_name = 'accounts/wallet.html'

    def get_context_data(self, **kwargs):
        ctx = super(WalletInfo, self).get_context_data(**kwargs)
        ctx['wallet'] = Wallet.objects.annotate(balance=Sum('operations__change')).prefetch_related(
            Prefetch('operations', queryset=Operation.objects.all().order_by('-date').select_related(
                'bet__event_participant__participant', 'bet__event_participant__event'))).get(user=self.request.user)
        return ctx

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% block content %}
	<div>
		<h1>Log In!</h1>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Log in!">
		</form>
	</div>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}


{% block content %}
	<div>
		<h1>Sign Up!</h1>
		<form method="post">
			{% csrf_token %}
			{{ form.as_p }}
			<input type="submit" value="Sign Up!">
		</form>
	</div>
{% endblock %}

accounts/templates/accounts/wallet.html
{% extends 'base.html' %}

{% block content %}
    <h2>Hi, {{ user.username }}!</h2>
    <p>Your saldo is: {{ wallet.balance|default_if_none:0 }} BTC</p>
    <br>
    <p><strong>List of your operations:</strong></p>
    <ul class="category-list">
        {% for op in wallet.operations.all %}
            {% with ep=op.bet.event_participant  %}
            <li>{{ op.change }}, {{ op.date }}, for option {{ ep.participant.name }}
                in <a href="{% url 'events:detail' pk=ep.event.pk %}">
                    {{ ep.event.name }}
                </a>
                event {% if ep.event.status != 'active' %} (finished){% endif %}
            </li>
            {% endwith %}
        {% endfor %}
    </ul>
{% endblock %}