Betting_page/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView

from Betting_page import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', RedirectView.as_view(pattern_name='events:list')),
    path('events/', include('events.urls', namespace='events')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('betting/', include('betting.urls', namespace='betting')),
    path('api/', include('Betting_page.api_urls')),
    path('api/auth', include('rest_framework.urls')),
]

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      url(r'^__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name = 'accounts'

urlpatterns = [
    path('signup/', views.SignUp.as_view(), name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('wallet/', views.WalletInfo.as_view(), name='wallet'),
]

events/urls.py
from django.urls import path

from events import views

app_name = 'events'

urlpatterns = [
    path('', views.EventsListView.as_view(), name='list'),
    path('<int:pk>/', views.EventDetailView.as_view(), name='detail'),
    path('category/', views.CategoryListView.as_view(), name='category_list'),
    path('category/<int:pk>/', views.CategoryDetailView.as_view(), name='category_detail'),
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Betting Page</title>
    <link rel="stylesheet" href='{% static 'Betting_page/css/style.css' %}'>
</head>
<body>
<nav class="navbar">
    <ul>
        <a href="{% url 'events:list' %}" style="float: left">Home</a>
        {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}">Log out</a>
            <a href="{% url 'accounts:wallet' %}">My wallet</a>
        {% else %}
            <a href="{% url 'accounts:signup' %}">Sign up</a>
            <a href="{% url 'accounts:login' %}">Log in</a>
        {% endif %}
        <a href="{% url 'events:category_list' %}">Category List</a>
        <a href="{% url 'events:list'%}?archive=true ">Archive</a>

    </ul>
</nav>

{% block content %}
{% endblock %}

</body>
</html>